services:
  golangback:
    build:
      context: ./golang-back
    image: back/golang
    ports:
      - "8081:8081"
  loadbalancer:
    image: haproxy
    ports:
      - "8383:8080"
    volumes:
      - ./node-user/haproxy:/usr/local/etc/haproxy

  # all needed container nodejs app
  nodeapp1:
    build:
      context: ./node-user
    image: nodeapp/js
    environment:
      - APPID=1111
  nodeapp2:
    image: nodeapp/js
    environment:
      - APPID=2222
  nodeapp3:
    image: nodeapp/js
    environment:
      - APPID=3333
  nodeapp4:
    image: nodeapp/js
    environment:
      - APPID=4444
